version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    groups:
      github-action-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/.github/workflows"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    groups:
      workflows-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 99
    groups:
      python-dependencies:
        patterns:
          - "*"
